odom_to_visual_odom:
  ros__parameters:
    use_vrpn: true
    odom_topic: /d2vins/odometry
    vrpn_topic: /mavros/vision_pose/pose
    visual_odom_topic: /fmu/in/vehicle_visual_odometry

sensor_combined_to_imu:
  ros__parameters:
    sensor_combined_topic: /fmu/out/sensor_combined
    vehicle_attitude_topic: /fmu/out/vehicle_attitude
    imu_topic: /mavros/imu/data_raw
